#+TITLE: KOH etch calculator
#+AUTHOR: Xavier Capaldi
#+DATE: [2020-08-23 Sun]
#+INDEX: code

In my microfabrication processes I often use KOH (potassium hydroxide/caustic potash/lye) to etch silicon and silicon dioxide.
The etch rate is dependent on KOH concentration and the temperature of the solution.
When working with delicate features, it is important to precisely control the etch. 
A web-based etch calculator makes it much easier to set up in the wet lab.

Previously I used an excellent [[http://www.lelandstanfordjunior.com/KOH.html][etch calculator by Maria Pace]] but it hasn't been working this year.
Instead, I could use the [[https://cleanroom.byu.edu/koh][data from the BYU Integrated Microfabrication Lab]] but it isn't very convenient.
With permission from the administrators at BYU, I extracted the data from their plots and fit them myself.
Using the fits I wrote a calculator in javascript which can estimate the etch rate and perform the dilution calculations.
It also displays warnings when you the etch parameters are known to cause issues in fabrication processes.
This was my first javascript program but it very functional.

[[file:koh-calculator.html][Use the etch and dilution calculators here]]

[[https://github.com/xcapaldi/koh-calculator][Checkout the source and my fitting methods on Github]]
